name: Move Linked Issue to Done When PR Merged

on:
  pull_request:
    types: [closed]

jobs:
  move_item:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Move card to Done
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          user: "MANISHIMWEPacifique"
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "Done"
          operation_mode: "status"
