name: Move Linked Issue to In Review

on:
  pull_request:
    types: [opened]

jobs:
  move_item:
    runs-on: ubuntu-latest

    steps:
      - name: Move card to In Review
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          user: "MANISHIMWEPacifique"
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "In Review"
          operation_mode: "status"
